### PR TITLE
Handle optional port

### PR DESCRIPTION
**Pull request by rnc**

### CODE REVIEW

**Comment by lcarva** [comment]
Testing this out, I'm seeing some inconsistencies. We don't currently have automated tests for this script, so I had to try things out manually. I believe we want the following behavior:

| authfile key | image ref | match? |
|---|---|---|
|quay.io | quay.io | :heavy_check_mark: |
|quay.io:443 | quay.io:443 | :heavy_check_mark: |
|quay.io | quay.io:443 | :heavy_check_mark: |
|quay.io:443 | quay.io | :heavy_check_mark: |
|quay.io:5000 | quay.io:5000 | :heavy_check_mark:  |
|quay.io:5000 | quay.io | :heavy_multiplication_x:  |
|quay.io | quay.io:5000 | :heavy_multiplication_x:  |
|quay.io/foobar | quay.io/foobar | :heavy_check_mark: |
|quay.io/foobar | quay.io/foobar/baz | :heavy_check_mark: |
|quay.io:443/foobar | quay.io:443/foobar | :heavy_check_mark: |
|quay.io/foobar | quay.io:443/foobar | :heavy_check_mark: |
|quay.io:443/foobar | quay.io/foobar | :heavy_check_mark: |
|quay.io:5000/foobar | quay.io:5000/foobar | :heavy_check_mark:  |
|quay.io:5000/foobar | quay.io/foobar | :heavy_multiplication_x:  |
|quay.io/foobar | quay.io:5000/foobar | :heavy_multiplication_x:  |

The above assume the port is 443 unless specified otherwise. I believe that's consistent with different OCI clients I've used in the past.

We also need to take into account that whether or not a port is present on the generated authfile should be based on whether or not the port is present in the given image ref. For example, calling the script with `quay.io:443` should return an authfile that contains a key for `quay.io:443` instead of just `quay.io`.

Also note that port numbers are not a main use case afaik. It's basically helpful for local development where you may have `localhost:5000` as the registry.

**Comment by zregvart** [comment]
Wouldn't the `.docker/config.json` contain the port if the port was used? I see `registry.127.0.0.1.nip.io:5000` present in mine.

**Comment by rnc** [comment]
@zregvart If a URL is constructed with 443 in it, then _currently_ select-oci-auth doesn't match. I don't believe it currently handles many of the scenarios @lcarva posted above.

Given so many combinations I think there is some need for test suite here :-)

@lcarva I think given your lines `quay.io 	quay.io:5000` and `quay.io 	quay.io:443` there is going to have to be special handling for 443 - or any port number is treated equivalently - for instance this PR could be modified to handle ports separately within the loop but that would break how you handle 5000 and 443 separately.

**Comment by lcarva** [comment]
If it helps, we can simplify things by not handling the port number differently. For example, `quay.io` only matches `quay.io` and `quay.io:443` only matches `quay.io:443`. I don't know if there's a strong need to handle the port number like I mentioned earlier. This would be my revised suggestion:

| authfile key | image ref | match? |
|---|---|---|
|quay.io | quay.io | :heavy_check_mark: |
|quay.io:443 | quay.io:443 | :heavy_check_mark: |
|quay.io | quay.io:443 | :heavy_multiplication_x: |
|quay.io:443 | quay.io | :heavy_multiplication_x: |
|quay.io:5000 | quay.io:5000 | :heavy_check_mark:  |
|quay.io:5000 | quay.io | :heavy_multiplication_x:  |
|quay.io | quay.io:5000 | :heavy_multiplication_x:  |
|quay.io/foobar | quay.io/foobar | :heavy_check_mark: |
|quay.io/foobar | quay.io/foobar/baz | :heavy_check_mark: |
|quay.io:443/foobar | quay.io:443/foobar | :heavy_check_mark: |
|quay.io/foobar | quay.io:443/foobar | :heavy_multiplication_x: |
|quay.io:443/foobar | quay.io/foobar | :heavy_multiplication_x: |
|quay.io:5000/foobar | quay.io:5000/foobar | :heavy_check_mark:  |
|quay.io:5000/foobar | quay.io/foobar | :heavy_multiplication_x:  |
|quay.io/foobar | quay.io:5000/foobar | :heavy_multiplication_x:  |

**Comment by rnc** [comment]
Closing this as https://github.com/konflux-ci/build-trusted-artifacts/pull/103 checks for the latter table which the current implementation supports.

**Pull request closed without merging**
