### PR TITLE
Switch to OCI artifacts

### PR DESCRIPTION
**Pull request by lcarva**
This changes the implementation to create/use artifacts on an OCI repository.

Work left:

- [ ] Fix/add acceptance tests.
- [ ] Decide if file storage support is to be retained - make changes accordingly.

### CODE REVIEW

**Comment by lcarva** [comment]
We may want to require a type prefix for `--store`, e.g. `--store=oci:quay.io/org/repo:tag`, or `--store=file:/workspaces/foobar`.

There's a bit of work required to support for **both** file and oci storage.

**Comment by zregvart** [comment]
> There's a bit of work required to support for **both** file and oci storage.

Do we see a future where we would support more than one implementation?

Right now I don't think we need both, we can decide on one and go forward with it... (Preferably OCI-based storage)

**Comment by lcarva** [comment]
> > There's a bit of work required to support for **both** file and oci storage.
> 
> Do we see a future where we would support more than one implementation?
> 
> Right now I don't think we need both, we can decide on one and go forward with it... (Preferably OCI-based storage)

Yeah. We should probably just switch over to using OCI. Let's see how the perf tests go before doing so.

**Comment by lcarva** [comment]
Dropping this in favor of https://github.com/konflux-ci/build-trusted-artifacts/pull/85.

**Pull request closed without merging**
